Add option to configure PostgreSQl
stuvusIT/confluence pull request #2
Opened 2018-07-04 14:03 UTC by dasJ

2018-07-04 16:21 UTC, SlothOfAnarchy approved these changes

2018-07-04 16:22 UTC, SlothOfAnarchy requested changes

2018-07-04 16:22 UTC, SlothOfAnarchy commented on defaults/main.yml
> +confluence_configure_postgres: true
Not documented

2018-07-07 12:49 UTC, dasJ commented on defaults/main.yml
> +confluence_configure_postgres: true
Fixed

2018-07-07 13:07 UTC, SlothOfAnarchy approved these changes

2018-07-07 13:08 UTC, merged